### PR TITLE
EE Release with lots of new spellbooks

### PR DESCRIPTION
**Pull request by wyakpara**
This release aims to add all full caster spellbooks to every mythic path with spellbook merge enabled, along with a few other spellbook combos, including:

- General compatibility for Divine classes for Lich
- Bard for Demon and Lich
- Warpriest for Angel

### CODE REVIEW

**Comment by vikigenius** [comment]
I suggest you remove any non full casters eg: Bard and Warpriest spellbooks from Angel and Lich respectively.

Because doing it will prevent you from getting higher level Angel and Lich spells.

**Comment by wyakpara** [comment]
Ohhh I didn’t even think about that. Tested angel with warpriest but wasn’t paying enough attention obviously. I’ll make the change and recommit a bit later. Thanks!

**Comment by wyakpara** [comment]
Warpriest and Bard removed from Angel and Lich, respectively.

**Comment by wyakpara** [comment]
Definitely tested with EE.  I can test with Pally shortly.

**Comment by wyakpara** [comment]
Ugh.  Well.  Computer issues currently.  Stay tuned; I'll double check Paladin once I have things settled and have a moment.

**Comment by wyakpara** [comment]
OK - confirmed, you can indeed get to 10th level spells with Pally merged with Angel.

Aside - to get other partial spellcasters to work with Angel/Lich, presumably you'd need to extend them the same way you do with Pally? I might try my hand at it later.

**Comment by vikigenius** [comment]
Yes, but the problem is that I have already extended some of them but only to some extend (eg: level 7 for Magus variants), redoing them to 9/10 would cause unintended results for earlier saves and mess with progressions of other merges and also your companions.

**Comment by vikigenius** [comment]
But thanks for the PR and testing, I will build locally and update the releases and mod version soon, and give you a shoutout for the contribution

**Comment by vikigenius** [comment]
For posterity, there are a few issues. Eldritch Scion was added but it does not have it's progression updated. This will be a problem since it won't get 7th level spells.

**Comment by vikigenius** [comment]
Actually never mind, it uses the Bard table which is updated already, so should not cause any issues.

**Comment by Mythalar** [comment]
He there,

I tested quite some of the new options, just one question :
Since the spell tables are the sames, could Skald be added to the mythic paths that can merge with Bards?

**Comment by vikigenius** [comment]
It's already there for almost all. Only Aeon is missing, I will try to add at some point in the future. You are welcome to create a PR as long as you have tested it.

**Pull request merged**
